"""Add cookies to user

Revision ID: 63f78443fa41
Revises: a09ac3a02ec2
Create Date: 2022-09-26 20:04:28.597604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f78443fa41'
down_revision = 'a09ac3a02ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_cookie', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_cookie')
    # ### end Alembic commands ###
